export default {
  welcome: {
    intro: {
      title: 'Bienvenido a {name}!',
      description: '{name} proporciona transcripción en tiempo real y traducción a múltiples idiomas para los servicios de su iglesia. Los miembros de la congregación pueden ver los subtítulos en vivo en sus teléfonos mediante código QR o enlace compartido.',
      button: 'Siguiente',
    },
    controls: {
      title: 'Controles',
      broadcast: 'Activar transmisión a pantallas y teléfonos',
      mic: 'Activar transcripción de voz a texto',
      settings: 'Abrir el panel de ajustes',
      button: 'Cerrar',
    },
  },
  general: {
    type_message: 'Escribe un mensaje',
    beta: 'BETA',
    update: 'Actualizar',
    subject_to_change: 'Sujeto a cambios',
  },
  snackbar: {
    version_mismatch: 'La aplicación de escritorio tiene una versión diferente a la versión web. Considere la posibilidad de actualizar, ya que la aplicación puede fallar.',
    no_speech: 'Tu navegador no es compatible con Web Speech API (Voz a Texto).',
    speech_recognition_error_event: {
      aborted: 'Dispositivo de audio en uso.',
      audio_capture: 'Falló la captura de audio.',
      network: 'Falló la comunicación de red necesaria para el reconocimiento.',
      not_allowed: 'Debes dar permiso para usar el micrófono.',
      service_not_allowed: 'El servicio de reconocimiento de voz no puede iniciarse debido a configuraciones o políticas.',
      bad_grammar: 'Hubo un problema con la lista de gramática del habla.',
      language_not_supported: 'El idioma de reconocimiento de voz no es compatible con el navegador.',
      unknown: 'Ocurrió un error desconocido de reconocimiento de voz.',
    },
    connections: {
      websocket: {
        opened: 'WebSocket abierto.',
        closed: 'WebSocket cerrado.',
      },
    },
  },
  settings: {
    title: 'Ajustes',
    general: {
      title: 'General',
      description: 'Ajustes generales de la aplicación',
      language: 'Selecciona el lenguaje de la interfaz',
      transcript: 'Descargar transcripción de la sesión',
      realtime_text: 'Actualizaciones de texto instantáneas',
      auto_open_web_app: 'Abrir aplicación web al iniciar',
      reset: {
        button: 'Restablecer todos los ajustes',
        dialog: {
          title: 'Restablecer ajustes',
          description: 'Está a punto de restablecer la configuración de toda la aplicación.',
          button: 'Restablecer',
        },
        snackbar: {
          title: 'Ajustes restablecidos',
          button: 'Cerrar',
        },
      },
    },
    stt: {
      title: 'Voz a Texto',
      description: 'Ajustes de voz a texto',
      type: 'Seleccione un servicio STT',
      sensitivity: 'Umbral de sensibilidad',
      sensitivity_start: 'Probar',
      sensitivity_stop: 'Parar',
      device: 'Escuchando: ',
      pinned_languages: 'Idiomas fijados',
      language: 'Seleccione un idioma de detección de voz',
      unsupported: {
        text: 'Web Speech API (Voz a Texto) solo está disponible en {link}. {kaomoji}',
        link: 'la página web',
        kaomoji: '(^・ω・^)',
      },
    },
    tts: {
      title: 'Texto a Voz',
      description: 'Ajustes de texto a voz',
      enabled: 'Activar la reproducción de texto a voz',
      type: 'Selecciona un servicio TTS',
      rate: 'Velocidad',
      pitch: 'Tono',
      language: 'Seleccione una voz de texto a voz',
      unsupported: {
        text: 'Texto a Voz solo está disponible en {link}. {kaomoji}',
        link: 'la página web',
        kaomoji: '(^・ω・^)',
      },
    },
    appearance: {
      title: 'Apariencia',
      description: 'Cambiar la apariencia de la aplicación',
      theme: 'Tema',
      footer: 'Ajustes del pie de página',
      footer_size: {
        hint: 'Tamaño del pie de página',
        options: [
          { title: 'Pequeño', value: 0 },
          { title: 'Grande', value: 1 },
        ],
      },
      text: {
        title: 'Ajustes de texto',
        font_family: 'Fuente',
        font_type: 'Tipo',
        font_size: 'Tamaño de letra',
        outline: {
          enabled: 'Contorno del texto',
          size: 'Tamaño del contorno',
          color: 'Color del contorno',
        },
        fade: 'Desvanecer el texto',
        fade_after: 'Desvanecer el texto después de',
        seconds: 'segundos',
        fade_for: 'Desvanecer el texto durante',
        new_line_delay: {
          hint: 'Iniciar nueva línea cuando no se envíe texto',
          options: [
            { title: 'Instantáneamente', value: 0 },
            { title: 'después de 2 segundos', value: 2 },
            { title: 'después de 4 segundos', value: 4 },
            { title: 'después de 6 segundos', value: 6 },
            { title: 'después de 8 segundos', value: 8 },
            { title: 'después de 10 segundos', value: 10 },
            { title: 'Nunca', value: -1 },
          ],
        },
        color: 'Color del texto',
        interim_color: 'Color del texto provisional',
      },
      ui: {
        title: 'Ajustes de interfaz',
        color: 'Color de fondo',
      },
    },
    word_replace: {
      title: 'Sustitución de palabras',
      description: 'Agregue palabras o frases para reemplazar aquí',
      enabled: 'Permitir reemplazar palabras o frases',
      match_whole_word: 'Solo palabras completas',
      match_case: 'Coincidir mayúsculas/minúsculas',
      info: 'Utilice el botón {icon} para agregar un nuevo reemplazo.',
      replacing: 'Reemplazando',
      replacement: 'Reemplazo',
    },
    translation: {
      title: 'Traducciones',
      description: 'Ajustes para traducir a otro idioma',
      warning: 'Las traducciones están en desarrollo. No confíe plenamente en ellas.',
      enabled: 'Habilitar traducciones',
      type: 'Seleccione un servicio de traducción',
      source: 'Fuente',
      target: 'Objetivo',
      show_original: 'Mostrar frase original antes de traducir',
      ml_notice: '{0} es una biblioteca basada en ML que utiliza recursos locales (CPU) para generar traducciones en su dispositivo. En dispositivos de gama baja, es posible que no funcione bien.',
      speech_lang: 'Tu idioma de voz a texto es ',
      unsupported: {
        text: 'Las traducciones solo están disponibles en {link}. {kaomoji}',
        link: 'la aplicación de escritorio',
        kaomoji: '(^・ω・^)',
      },
    },
    connections: {
      title: 'Conexiones',
      description: 'Enviar datos a otras aplicaciones cuando se utiliza {icon}',
      action: {
        add: 'Utilice el botón {icon} para agregar una nueva conexión',
      },
      http_server: {
        title: 'Servidor de Visualización HTTP',
        running: 'Servidor ejecutándose en el puerto {port}',
        stopped: 'Servidor detenido',
      },
      cloudflare: {
        title: 'Túnel de Cloudflare',
        starting: 'Iniciando túnel...',
        running: 'Túnel activo',
        stopped: 'Túnel inactivo',
        warning: 'Expone su servidor de transcripción a internet. Cualquier persona con la URL puede ver las transcripciones.',
        copied: 'URL del túnel copiada al portapapeles',
        requires_http: 'Primero habilite el servidor HTTP',
        error: {
          not_installed: 'cloudflared no encontrado. Instalar desde cloudflare.com/products/tunnel',
          failed: 'Falló al iniciar el túnel',
        },
      },
      info: {
        title: 'Información de conexión de red',
        description: 'Otros dispositivos pueden conectarse usando estas URLs',
        local_addresses: 'Direcciones IP locales',
        no_interfaces: 'No se encontraron interfaces de red',
      },
      dialog: {
        title: {
          add: 'Agregar conexión',
          edit: 'Editar conexión',
        },
        description: {
          websocket: 'Envía actualizaciones de texto en tiempo real a través de un websocket',
          webhook: 'Enviar actualizaciones de texto a través de una solicitud POST de webhook',
        },
        field: {
          title: 'Título',
          type: 'Tipo',
          address: 'Dirección',
          port: 'Puerto',
          password: 'Contraseña',
          password_placeholder: 'Si la autenticación del servidor está deshabilitada, deje este campo vacío.',
          full_address: 'Dirección completa',
        },
        action: {
          cancel: 'Cancelar',
          confirm: 'Confirmar',
          delete: 'Eliminar',
        },
      },
    },
  },
}
