// i18n Romanian translations
export default {
  welcome: {
    intro: {
      title: 'Bine ați venit la {name}!',
      description: '{name} oferă transcriere în timp real și traducere în mai multe limbi pentru serviciile bisericii dumneavoastră. Membrii congregației pot vizualiza subtitrările live pe telefoanele lor prin cod QR sau link partajat.',
      button: 'Următorul',
    },
    controls: {
      title: 'Comenzi',
      broadcast: 'Activează transmisia pe ecrane și telefoane',
      mic: 'Activează transcrierea voce-în-text',
      settings: 'Deschide panoul de setări',
      button: 'Închide',
    },
  },
  general: {
    type_message: 'Scrieți un mesaj',
    beta: 'BETA',
    update: 'Actualizare',
    subject_to_change: 'Supus modificărilor',
  },
  snackbar: {
    version_mismatch: 'Aplicația desktop are o versiune diferită față de versiunea web. Luați în considerare actualizarea, deoarece pot apărea erori.',
    no_speech: 'Browserul dumneavoastră nu suportă Web Speech API (Voce-în-text).',
    speech_recognition_error_event: {
      aborted: 'Dispozitivul audio este utilizat.',
      audio_capture: 'Captarea audio a eșuat.',
      network: 'Comunicarea de rețea necesară pentru recunoaștere a eșuat.',
      not_allowed: 'Trebuie să acordați permisiunea de utilizare a microfonului.',
      service_not_allowed: 'Serviciul de recunoaștere vocală nu poate fi pornit din cauza setărilor sau politicilor.',
      bad_grammar: 'A apărut o problemă cu lista de gramatică a vorbirii.',
      language_not_supported: 'Limba de recunoaștere vocală nu este suportată de browser.',
      unknown: 'A apărut o eroare necunoscută de recunoaștere vocală.',
    },
    connections: {
      websocket: {
        opened: 'WebSocket deschis.',
        closed: 'WebSocket închis.',
      },
    },
  },
  settings: {
    title: 'Setări',
    general: {
      title: 'General',
      description: 'Setări generale ale aplicației',
      language: 'Selectați limba interfeței',
      transcript: 'Descărcați transcrierea sesiunii',
      realtime_text: 'Actualizări instantanee de text',
      auto_open_web_app: 'Deschide aplicația web la pornire',
      reset: {
        button: 'Resetați toate setările',
        dialog: {
          title: 'Resetare setări',
          description: 'Sunteți pe cale să resetați setările întregii aplicații.',
          button: 'Resetare',
        },
        snackbar: {
          title: 'Setări resetate',
          button: 'Închide',
        },
      },
    },
    stt: {
      title: 'Voce-în-Text',
      description: 'Setări voce-în-text',
      type: 'Selectați un serviciu STT',
      sensitivity: 'Prag de sensibilitate',
      sensitivity_start: 'Verificare',
      sensitivity_stop: 'Oprire',
      device: 'Ascultare: ',
      pinned_languages: 'Limbi fixate',
      language: 'Selectați o limbă de detectare vocală',
      unsupported: {
        text: 'Web Speech API (Voce-în-Text) este disponibil doar pe {link}. {kaomoji}',
        link: 'versiunea web',
        kaomoji: '(^・ω・^)',
      },
    },
    tts: {
      title: 'Text-în-Voce',
      description: 'Setări text-în-voce',
      enabled: 'Activați redarea vocală text-în-voce',
      type: 'Selectați un serviciu TTS',
      rate: 'Viteză',
      pitch: 'Tonalitate',
      language: 'Selectați o voce text-în-voce',
      unsupported: {
        text: 'Text-în-Voce este disponibil doar pe {link}. {kaomoji}',
        link: 'versiunea web',
        kaomoji: '(^・ω・^)',
      },
    },
    appearance: {
      title: 'Aspect',
      description: 'Schimbați aspectul aplicației',
      theme: 'Temă',
      footer: 'Setări subsol',
      footer_size: {
        hint: 'Dimensiune subsol',
        options: [
          { title: 'Mic', value: 0 },
          { title: 'Mare', value: 1 },
        ],
      },
      text: {
        title: 'Setări text',
        font_family: 'Familie de fonturi',
        font_type: 'Tip',
        font_size: 'Dimensiune font',
        outline: {
          enabled: 'Contur text',
          size: 'Dimensiune contur text',
          color: 'Culoare contur text',
        },
        fade: 'Estompare text',
        fade_after: 'Estompare text după',
        seconds: 'secunde',
        fade_for: 'Estompare text pentru',
        new_line_delay: {
          hint: 'Începeți o linie nouă când nu se trimite text',
          options: [
            { title: 'Instantaneu', value: 0 },
            { title: 'după 2 secunde', value: 2 },
            { title: 'după 4 secunde', value: 4 },
            { title: 'după 6 secunde', value: 6 },
            { title: 'după 8 secunde', value: 8 },
            { title: 'după 10 secunde', value: 10 },
            { title: 'Niciodată', value: -1 },
          ],
        },
        color: 'Culoare text',
        interim_color: 'Culoare text provizoriu',
      },
      ui: {
        title: 'Setări interfață',
        color: 'Culoare fundal',
      },
    },
    word_replace: {
      title: 'Înlocuire cuvinte',
      description: 'Adăugați cuvinte sau expresii de înlocuit aici',
      enabled: 'Activați înlocuirea cuvintelor sau expresiilor',
      match_whole_word: 'Doar cuvinte întregi',
      match_case: 'Potrivire majuscule/minuscule',
      info: 'Folosiți butonul {icon} pentru a adăuga o nouă înlocuire!',
      replacing: 'Înlocuire',
      replacement: 'Înlocuitor',
    },
    translation: {
      title: 'Traduceri',
      description: 'Setări pentru traducerea în altă limbă',
      warning: 'Traducerile sunt în curs de dezvoltare. Nu vă bazați pe ele ca fiind perfecte!',
      enabled: 'Activați traducerile',
      type: 'Selectați un serviciu de traducere',
      source: 'Sursă',
      target: 'Țintă',
      show_original: 'Afișați fraza originală înainte de traducere',
      ml_notice: '{0} este o bibliotecă bazată pe ML care utilizează resurse locale (CPU) pentru a genera traduceri pe dispozitivul dumneavoastră. Pe calculatoare mai slabe, poate să nu funcționeze bine.',
      speech_lang: 'Limba dumneavoastră voce-în-text este ',
      unsupported: {
        text: 'Traducerile sunt disponibile momentan doar pe {link}. {kaomoji}',
        link: 'versiunea desktop',
        kaomoji: '(^・ω・^)',
      },
    },
    connections: {
      title: 'Conexiuni',
      description: 'Trimiteți date către alte aplicații când folosiți {icon}',
      action: {
        add: 'Folosiți butonul {icon} pentru a adăuga o nouă conexiune',
      },
      http_server: {
        title: 'Server de Afișare HTTP',
        running: 'Server rulează pe portul {port}',
        stopped: 'Server oprit',
      },
      cloudflare: {
        title: 'Tunel Cloudflare',
        starting: 'Se pornește tunelul...',
        running: 'Tunel activ',
        stopped: 'Tunel inactiv',
        warning: 'Expune serverul de transcriere pe internet. Oricine are URL-ul poate vizualiza transcrierile.',
        copied: 'URL-ul tunelului copiat în clipboard',
        requires_http: 'Activați mai întâi serverul HTTP',
        error: {
          not_installed: 'cloudflared nu a fost găsit. Instalați de la cloudflare.com/products/tunnel',
          failed: 'Pornirea tunelului a eșuat',
        },
      },
      info: {
        title: 'Informații Conexiune Rețea',
        description: 'Alte dispozitive se pot conecta folosind aceste URL-uri',
        local_addresses: 'Adrese IP Locale',
        no_interfaces: 'Nu s-au găsit interfețe de rețea',
      },
      dialog: {
        title: {
          add: 'Adaugă conexiune',
          edit: 'Editează conexiune',
        },
        description: {
          websocket: 'Trimite actualizări text prin websocket',
          webhook: 'Trimite actualizări text prin cerere POST webhook',
        },
        field: {
          title: 'Titlu',
          type: 'Tip',
          address: 'Adresă',
          port: 'Port',
          password: 'Parolă',
          password_placeholder: 'Dacă autentificarea serverului este dezactivată, lăsați acest câmp gol.',
          full_address: 'Adresă completă',
        },
        action: {
          cancel: 'Anulează',
          confirm: 'Confirmă',
          delete: 'Șterge',
        },
      },
    },
  },
}
